sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen docs/Doxyfile.default
  - touch docs/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GITHUB_REPO_TOKEN
  on:
    branch: master
